_base_: 'default_feature.yml'

data:
  dataset: ego4d_howto100_feat 
  root: pnorm:s3://my_ego4d/videomae_L14_feature_fps8/
  # metadata: /mnt/petrelfs/xujilan/data/ego4d/generated/ego4d_train_nounverb_v3.json
  metadata: /mnt/petrelfs/xujilan/data/ego4d/generated/ego4d_train_nounverb_v3_debug.json

  howto_root: pnorm:s3://HT100M/internvideo_MM_L14/
  # howto_metadata: /mnt/petrelfs/xujilan/data/egohowto_pairdata/htm_llama3_refined.json
  howto_metadata: /mnt/petrelfs/xujilan/data/egohowto_pairdata/htm_llama3_debug.json

  # clip_length: 4
  clear_narration: true
  load_from: ceph

model:
  name: CLIP_FEAT_LARGE_OPENAI
  num_frames: ${data.clip_length}
  project_embed_dim: 768

train:
  batch_size: 4 
  epochs: 20

test:
  testonly: true
  ek100_mir:
    root: pnorm:s3://epic_kitchen/videomae_L14_feature_fps8/
    load_from: ceph
  youcook:
    root: pnorm:s3://YouCook2/exo_internvideo_MM_L14_features/
    load_from: ceph
  charades_egoexo:
    ego_root: pnorm:s3://charades_ego/videomae_L14_feature_fps8/
    exo_root: pnorm:s3://charades_ego/internvideo_MM_L14_features/
    load_from: ceph
  egolearn:
    ego_root: pnorm:s3://ourdata/videomae_L14_feature_fps8/
    exo_root: pnorm:s3://ourdata/exo_internvideo_MM_L14_features/
    load_from: ceph
  egomcq:
    root: pnorm:s3://my_ego4d/videomae_L14_feature_fps8/
  youcook_video:
    root: pnorm:s3://YouCook2/exo_internvideo_MM_L14_features/
    load_from: ceph
  egosumm:
    root: pnorm:s3://my_ego4d/videomae_L14_feature_fps8/

resume: /mnt/petrelfs/xujilan/exps/egoinstructor/best_checkpoint/checkpoint.pt
output: /mnt/petrelfs/xujilan/exps/egoinstructor/test/
